default/objects/Trigger_Execution_Log__c/Trigger_Execution_Log__c.object-meta.xml
<CustomObject>
    <description>Log of trigger execution logic for debugging.</description>
    <label>Trigger Execution Log</label>
    <nameField>
        <displayFormat>TEL-{000000}</displayFormat>
        <label>Trigger Execution Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Execution Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Trigger_Execution_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The log of execution events</description>
    <inlineHelpText>The log of execution events</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Trigger_Execution_Log__c/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <label>Related Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Trigger_Execution_Log__c/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Trigger_Execution_Log__c/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

default/objects/Trigger_Execution_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trigger_Execution_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Trigger_Log_Link__c/Trigger_Log_Link__c.object-meta.xml
<CustomObject>
    <description>Relates a specific sObject to a trigger execution log</description>
    <label>Trigger Log Link</label>
    <nameField>
        <displayFormat>TLL-{00000}</displayFormat>
        <label>Trigger Log Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Log Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Trigger_Log_Link__c/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Trigger_Log_Link__c/fields/Trigger_Execution_Log__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Execution_Log__c</fullName>
    <label>Trigger Execution Log</label>
    <referenceTo>Trigger_Execution_Log__c</referenceTo>
    <relationshipLabel>Trigger Log Links</relationshipLabel>
    <relationshipName>Trigger_Log_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to apex triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

default/objects/Trigger_Settings__c/fields/Enable_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>should Apex triggers with logging enabled write logs to the Trigger_Execution_Log__c object?</description>
    <inlineHelpText>should Apex triggers with logging enabled write logs to the Trigger_Execution_Log__c object?</inlineHelpText>
    <label>Enable Logging</label>
    <type>Checkbox</type>
</CustomField>

default/classes/LogViewerController.cls
public without sharing class LogViewerController {
    @AuraEnabled(cacheable=false)
    public static List<Trigger_Execution_Log__c> getLogs(Id recordId) {

        String sObjectType = recordId.getSObjectType().getDescribe().getName();

        system.debug('Getting logs for record: ' + recordId + ' of type ' + sObjectType);

        sObject recordDetails = database.query('SELECT CreatedDate FROM ' +SObjectType+' WHERE ID = :recordId');
        dateTime timeStamp = (DateTime)recordDetails.get('CreatedDate');

        // Step 1: Find all logs linked to the record via junction object
        List<Trigger_Log_Link__c> links = [
            SELECT Trigger_Execution_Log__c
            FROM Trigger_Log_Link__c
            WHERE Related_Record_Id__c = :recordId
        ];

        system.debug('\n\n\n---- Found ' + links.size()+' links\n\n');
        system.debug(links);
   
        Set<Id> logIds = new Set<Id>();
        for (Trigger_Log_Link__c link : links) {
            logIds.add(link.Trigger_Execution_Log__c);
        }

        if (logIds.isEmpty()) return new List<Trigger_Execution_Log__c>();

        DateTime minTime = timeStamp.addSeconds(-2);
        DateTime maxTime = timeStamp.addSeconds(2);
        // Step 2: Fetch log records
        return [
            SELECT Id, Message__c, Timestamp__c, Context__c, SObject_Type__c, Trigger_Name__c, User__c, CreatedDate
            FROM Trigger_Execution_Log__c
            WHERE Id IN :logIds  OR (
                Context__c = 'before_insert' AND 
                SObject_Type__c = :sObjectType AND 
                Timestamp__c >= :minTime AND Timestamp__c <= :maxTime
            )
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=false)
    public static boolean getIsLoggingEnabled(){
        Trigger_Settings__c settings = Trigger_Settings__c.getOrgDefaults();
        boolean isLoggingEnabled = settings != null && settings.Enable_Logging__c;
        return isLoggingEnabled;
    }
}